CREATE KEYSPACE gestionEscolar_lab8 WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor':1};
use gestionEscolar_lab8;


create table ESCUELAS(
CLAVE VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
DIRECCION VARCHAR,
CD VARCHAR
);

CREATE TABLE DOCENTE(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TEL VARCHAR,
NOBANCARIA VARCHAR,
NOTELINS INT,
AREAESPECIALIDAD VARCHAR,
GRADOESTUDIO VARCHAR,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR,
NOOFICINA VARCHAR
);

drop table alumnos;
CREATE TABLE ALUMNOS(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
FECHANAC VARCHAR,
TUTOR VARCHAR,
CREDITO BOOLEAN,
GRADOACADEMICO VARCHAR,
FECHAINCRIPCION VARCHAR,
ESCUELA VARCHAR
);

DROP TABLE ALUMNOS_ESCUELA;
CREATE TABLE ALUMNOS_ESCUELA(
CURP VARCHAR,
NOMBRE VARCHAR,
FECHANAC VARCHAR,
TUTOR VARCHAR,
CREDITO BOOLEAN,
GRADOACADEMICO VARCHAR,
FECHAINCRIPCION VARCHAR,
ESCUELA VARCHAR,
PRIMARY KEY(ESCUELA, CURP)
);

CREATE TABLE ADMINISTRATIVOS(
CURP VARCHAR PRIMARY KEY,
ESCUELA VARCHAR,
EXTTEL VARCHAR,
FUNCION VARCHAR,
HRENTRADA VARCHAR,
HRSALIDA VARCHAR,
MAIL VARCHAR,
NOBANCARIA VARCHAR,
NOMBRE VARCHAR,
TEL VARCHAR
);

CREATE TABLE MANTENIMIENTO(
CURP VARCHAR PRIMARY KEY,
AREAESPECIALIDAD VARCHAR,
ESCUELA VARCHAR,
NOBANCARIA VARCHAR,
NOMBRE VARCHAR,
NOTELINS VARCHAR,
TEL VARCHAR
);

CREATE TABLE MANTENIMIENTO_ESCUELA(
escuela text,
curp text,
areaespecialidad text,
nobancaria text,
nombre text,
notelins text,
tel text,
PRIMARY KEY (escuela, curp)
);

/*Q1. Todos los Docentes de una escuela*/
CREATE TABLE Q1(
CURP VARCHAR,
NOMBRE VARCHAR,
TEL VARCHAR,
NOBANCARIA VARCHAR,
NOTELINS INT,
AREAESPECIALIDAD VARCHAR,
GRADOESTUDIO VARCHAR,
TUTORIAFIRMADA BOOLEAN,
ESCUELA VARCHAR,
NOOFICINA VARCHAR,
PRIMARY KEY (ESCUELA, CURP)
);

/*Q2. Todos los alumnos de un Docente*/
CREATE TABLE Q2(
CURP VARCHAR,
NOMBRE VARCHAR,
FECHANAC VARCHAR,
TUTOR VARCHAR,
CREDITO BOOLEAN,
GRADOACADEMICO VARCHAR,
FECHAINCRIPCION VARCHAR,
ESCUELA VARCHAR,
PRIMARY KEY(TUTOR,CURP )
);

/*Q3. Todos los administrativos de una escuela*/
CREATE TABLE Q3(
CURP VARCHAR,
ESCUELA VARCHAR,
EXTTEL VARCHAR,
FUNCION VARCHAR,
HRENTRADA VARCHAR,
HRSALIDA VARCHAR,
MAIL VARCHAR,
NOBANCARIA VARCHAR,
NOMBRE VARCHAR,
TEL VARCHAR,
PRIMARY KEY (ESCUELA, CURP)
);